#!/usr/bin/env node
/**
 * Pre-compute waveform peaks for SON projects.
 *
 *   node scripts/peaks.mjs
 *
 * For each audio slug below, if a local file exists at
 *   public/audio/<slug>.{mp3,wav,m4a}
 * it is decoded with ffmpeg (must be on PATH) to mono f32 PCM and
 * downsampled to PEAKS normalized amplitudes. If no file is found, a
 * deterministic synthetic waveform is generated so the UI renders during
 * development. Output is written to content/peaks.generated.ts.
 *
 * Replace the demo SoundHelix URLs in content/projects.ts with local files
 * and re-run this script to bake real peaks.
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const PEAKS = 200; // bars per track
const SLUGS = ["basse-continue", "hors-champ", "regie-nuit", "marge-brute"];

function findAudio(slug) {
  for (const ext of ["mp3", "wav", "m4a", "flac"]) {
    const p = resolve(root, "public/audio", `${slug}.${ext}`);
    if (existsSync(p)) return p;
  }
  return null;
}

function decodeWithFfmpeg(file) {
  // mono, 8kHz, 32-bit float, raw — small + fast, enough for peaks
  const buf = execFileSync(
    "ffmpeg",
    ["-v", "quiet", "-i", file, "-ac", "1", "-ar", "8000", "-f", "f32le", "-"],
    { maxBuffer: 1 << 28 },
  );
  const samples = new Float32Array(
    buf.buffer,
    buf.byteOffset,
    Math.floor(buf.byteLength / 4),
  );
  const block = Math.floor(samples.length / PEAKS) || 1;
  const out = [];
  let max = 0;
  for (let i = 0; i < PEAKS; i++) {
    let peak = 0;
    for (let j = 0; j < block; j++) {
      const v = Math.abs(samples[i * block + j] || 0);
      if (v > peak) peak = v;
    }
    out.push(peak);
    if (peak > max) max = peak;
  }
  return out.map((v) => +(v / (max || 1)).toFixed(3));
}

// deterministic PRNG (mulberry32) seeded from the slug
function seeded(slug) {
  let h = 1779033703 ^ slug.length;
  for (let i = 0; i < slug.length; i++) {
    h = Math.imul(h ^ slug.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  let a = h >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function synth(slug) {
  const rnd = seeded(slug);
  const out = [];
  for (let i = 0; i < PEAKS; i++) {
    const t = i / PEAKS;
    // musical envelope: intro swell, sustained body, outro fade
    const env =
      Math.sin(Math.PI * t) * 0.7 + 0.3 - Math.max(0, t - 0.85) * 1.5;
    const transient = rnd() < 0.08 ? 0.4 : 0;
    const detail = (rnd() * 0.5 + Math.abs(Math.sin(i * 0.6)) * 0.5) * 0.6;
    out.push(+Math.max(0.04, Math.min(1, env * detail + transient)).toFixed(3));
  }
  return out;
}

const result = {};
for (const slug of SLUGS) {
  const file = findAudio(slug);
  if (file) {
    try {
      result[slug] = decodeWithFfmpeg(file);
      console.log(`✓ ${slug} — decoded ${file}`);
      continue;
    } catch (e) {
      console.warn(`! ${slug} — ffmpeg failed (${e.message}); using synth`);
    }
  } else {
    console.log(`· ${slug} — no local audio; using synthetic peaks`);
  }
  result[slug] = synth(slug);
}

const banner = `// AUTO-GENERATED by scripts/peaks.mjs — do not edit by hand.
// ${PEAKS} normalized (0..1) amplitudes per track.\n`;
const body = `export const peaks: Record<string, number[]> = ${JSON.stringify(
  result,
)};\n`;

const outPath = resolve(root, "content/peaks.generated.ts");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, banner + body);
console.log(`\nWrote ${outPath}`);

// keep the linter happy about the unused import in some setups
void readFileSync;
